name: gabaydiwa
description: "GabayDiwa App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  pdf: ^3.10.8
  printing: ^5.11.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0

# Configuration for Flutter Launcher Icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/gabaydiwa_logo.png"
  min_sdk_android: 21
  
  # Adds white background behind your PNG icon for modern Android
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/gabaydiwa_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/